#!/usr/bin/env python 

import subprocess

interface =input("enter your internet interface : ")
mac=input ("enter your new mac :")

print ("[+] changing MAC address for --> "+interface)
print ("[+] changinh MAC address to --> "+mac)

subprocess.call([" ifconfig" , interface , "down"])
subprocess.call([" ifconfig" , interface , "hw ether", mac])
subprocess.call([" ifconfig" , interface , "up"])
